### ISSUE TITLE
Spinners?

### ISSUE THREAD

**Issue by verygreenboi** [eluleci/FlatUI#10]
Hi, nice work. I wonder if you've thought about putting Spinners in the library. In the interim if I wanted to style my Spinners to have a theme in the library how do I do that? Thanks again.

**Comment by eluleci** [comment]
You can use a custom view for you spinner and use FlatTextView in that custom view instead of TextView. Here is an answer. http://stackoverflow.com/questions/18312043/how-to-change-spinner-text-color
If you follow the second answer and use FlatTextView instead, you can use it in spinner.
