### ISSUE TITLE
Prefix resources to ignore resource name clashes

### ISSUE THREAD

**Issue by kloon15** [eluleci/FlatUI#15]
You should prefix the library resources using the new android gradle option to avoid name clashes with other libraries:

```
android {
  resourcePrefix 'mylib_'
}
```

**Comment by eluleci** [comment]
can you give more detailed explanation or a url for a kind of documentation about this?

**Comment by kloon15** [comment]
Not really, it's just documented here:
http://tools.android.com/tech-docs/new-build-system

2014-05-29 17:06 GMT+02:00 Emrullah Lüleci notifications@github.com:

**Comment by eluleci** [comment]
Fixed with 2.1.0. Thanks to @aimanbaharum.
