### ISSUE TITLE
Strange Issue on  Consecutive Activity Opening. 

### ISSUE THREAD

**Issue by amank22** [eluleci/FlatUI#18]
![screenshot_2014-06-21-10-32-40](https://cloud.githubusercontent.com/assets/3993720/3347884/149850b8-f902-11e3-9e87-4249e0822080.png)
![screenshot_2014-06-21-10-32-08](https://cloud.githubusercontent.com/assets/3993720/3347885/14991642-f902-11e3-89f4-eb426295e169.png)
![screenshot_2014-06-21-10-32-20](https://cloud.githubusercontent.com/assets/3993720/3347886/149bd288-f902-11e3-8070-216b621484dc.png)
![screenshot_2014-06-21-10-32-27](https://cloud.githubusercontent.com/assets/3993720/3347887/14a0d120-f902-11e3-83f8-09bad4e11fef.png)
![screenshot_2014-06-21-10-32-33](https://cloud.githubusercontent.com/assets/3993720/3347888/14a221ec-f902-11e3-983d-05a4d6298b2a.png)

The editbox and buttons gets rounded and border width gets broader each time i open the activity and goes back to normal to restarting application.
Also this affects all the activities and radiobuttons stop working/or doesn't show to be working.

**Comment by KOFLazycat** [comment]
I have the same question. Have you solved it ?

**Comment by amank22** [comment]
No,i have removed the library and done work on my own.

**Comment by eluleci** [comment]
fixed with pull request from @michalbrz. sorry for late merge. I had problems about my device and gradle
