### ISSUE TITLE
cornerRadius

### ISSUE THREAD

**Issue by Volkanugr** [eluleci/FlatUI#19]
hello 

Error:Attribute "cornerRadius" has already been defined

i wantto make a change but while compiling sources are redefine how can i fix it ? 

my build.gradle

```
compile 'com.github.eluleci:flatui:2.0.2'
compile 'com.github.dmytrodanylyk.circular-progress-button:library:1.0.2'
```

**Comment by eluleci** [comment]
Fixed with 2.1.0
