### ISSUE TITLE
Hi, can't seem to work with Fragments for a slide menu project 

### ISSUE THREAD

**Issue by TFU1** [eluleci/FlatUI#25]
Hi, can't seem to work with adding FlatUI xml elements into Fragments xml file for a slide menu project after following the instruction of adding xmlns and adding some FlatUI element xml on it.  It seems intuitive to me to follow as stated by adding the FlatUI xml into the fragments xml.

This is the Slide Menu project
https://github.com/benjiwsp/SlideMenu-Android

Let me know, or maybe i'll just not use Flat.. haha

**Comment by eluleci** [comment]
I am sorry but I didn't find any usage of this library in your project. There is no commit since May 11. Please check your project. And when you use this library please don't create any issue because of your projects faults.
