### ISSUE TITLE
Error:Attribute "theme" has already been defined

### ISSUE THREAD

**Issue by anshul1235** [eluleci/FlatUI#26]
In /app/build/intermediates/exploded-aar/com.google.android.gms/play-services/4.4.52/res/values/wallet_attrs.xml

Please tell why this is happening when i am trying to compile your library

**Comment by eluleci** [comment]
This is happening because both of the libraries were using the attribute "theme" but it is fixed with the version 2.1.0. Now you can use the attribute "fl_theme" to set the theme.
