### ISSUE TITLE
Remove AppComp dependency

### ISSUE THREAD

**Issue by soarcn** [eluleci/FlatUI#3]
I would suggest drop AppComp dependency out from this library, only provide actionbar background drawable producer function in this library, and developer can change the actionbar bg by themself.
It's always good to keep library simple and less dependency, besides there still huge amount of people using ABS now.

**Comment by eluleci** [comment]
I was also thinking about removing the dependency or creating two different
repository (one for app compat). I'll make changes as soon as possible.

**Comment by eluleci** [comment]
I removed dependency to compatibility library. Maven repo is updated and you can use it with:

'com.github.eluleci:flatui:0.1.2'

**Comment by soarcn** [comment]
@eluleci should be 'com.github.eluleci:flatui:0.1.2@aar' :)

**Comment by eluleci** [comment]
What is the point of using @aar at the end of repository? And also I haven't seen this kind of usage in any place.

**Comment by soarcn** [comment]
instruction of aar:http://tools.android.com/tech-docs/new-build-system/aar-format
Since this library contain not only java code but also resources(assets), you have to package it to aar format as you already done.
if you do not add @aar, gradle will try to download jar file instead of aar file.

**Comment by eluleci** [comment]
I think aar file is downloaded by default. If you try to use the library without @aar suffix, you'll see that font files are also available (assets). In my case it is working but I saw the same thing you said in some pages. So I am not sure about the best usage of it.
