### ISSUE TITLE
Flat Ui in Android using Android Studio

### ISSUE THREAD

**Issue by chintan90** [eluleci/FlatUI#30]
I am using Flat Ui in my Android Application using Android Studio but i am unable to find AutoCompleteTextView inside Flat Ui and I have to use AutoCompleteTextview in my application so anyone suggest me the way to use that?

**Comment by eluleci** [comment]
There is no AutoCompleteTextView implementation in this library yet. You can fork the library and add it yourself. You can look at implementation of FlatTextView for it. Sorry. I'll try to add it someday.

**Comment by chintan90** [comment]
But i can only use dependency in my project so how should i add it and how can i use dependency after that? can u tell me?

**Comment by sherwinrobles** [comment]
Hi eluleci, great library! :) I just fork  AutoCompleteTextView  based from your code hope its ok.

Hi chintan90 for a while you could check this:  http://stackoverflow.com/questions/25192771/flat-ui-in-android-studio/25772188#25772188
