### ISSUE TITLE
Documentation - Samples

### ISSUE THREAD

**Issue by cheenu** [eluleci/FlatUI#31]
I tried this but it doesn't work (gives an error `Error parsing XML: unbound prefix`)

```
<com.cengalabs.flatui.views.FlatEditText
    ...
    flatui:fl_fieldStyle="flat" />
```

However, this works

```
<com.cengalabs.flatui.views.FlatEditText
    ...
    fl_fieldStyle="flat" />
```

If the latter is the expected behaviour, maybe the documentation can be updated.

**Comment by cheenu** [comment]
Actually, scratch that ... I just tried 

```
<com.cengalabs.flatui.views.FlatEditText
    ...
    fl_fieldStyle="box" />
```

and it didn't change to box style (although it doesn't give an error, compiles fine)

What am I doing wrong?

**Comment by cheenu** [comment]
Using the latest version (`2.1.1`) btw

**Comment by eluleci** [comment]
If it says unbound prefix it means that you didn't add the **namespace** to your layout file. If you look at the [main layout of the sample project](https://github.com/eluleci/FlatUI/blob/master/sample/src/main/res/layout/activity_main.xml) you'll see there is **namespace** added at 3rd line. Do you have it there?

**Comment by cheenu** [comment]
Right, thats it. Knew I was missing something simple. :smile:

**Comment by eluleci** [comment]
it is always because of small things :D nice that it is fixed
