### ISSUE TITLE
How to use in Eclipse

### ISSUE THREAD

**Issue by NiranjanShah** [eluleci/FlatUI#35]
Hello Eluleci,

How to we use the FlatUI in Eclipse IDE, had googled a lot, however no HELP was found.

Regards,

**Comment by eluleci** [comment]
I haven't tried to use this with eclipse before but I can give you some suggestions.

If you use Gradle in your Eclipse project just add the dependency to your project.

If the project has the old Android Project structure you can do the followings.
- create a package in your project and copy all the .java files and packages from the **com.cengalabs.flatui** package
- then copy the **attrs.xml** and **colors.xml** files from the library into your project's **res** directory
- if you are using the fonts, you must also copy the **assets** folder into your project's **assets** folder
- while using the views, you must point to the package that you put the views package to. ex:

```
<your.package.name.views.FlatTextView
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    flatui:fl_fieldStyle="flat" />
```

This is the only solution I can figure out. But if there is a new update in the library you need to get the changed files again and put into your project. (if you need the new changes)

I hope that works for you. Please tell me if it works or not, to close the issue.

**Comment by NiranjanShah** [comment]
Thank you very much for the reply, really appreciate and I am thankful @
the same time, I have done the needful and was able to run the sample app,
however when I am using the flat edittext in my app, @ the run time it is
giving error stating flatrdittext cannot be cast to view group...

Request your input for the same.

BTw,it is Diwali in India and it is one of the major festivalof India and
it is also a new year for us so I would like to take this opportunity to
wish you and your family a Happy Diwali and a prosperous New year...

Regards

**Comment by eluleci** [comment]
Thank you very much, you're so kind. I wish you a happy new year too. :)

For the error, if you could give the error log I may look at the problem.
