### ISSUE TITLE
Can we changing color?

### ISSUE THREAD

**Issue by mynameismaxz** [eluleci/FlatUI#37]
in FlatUI Library can we change the color for that themes. and how can i change it? thanks a lot :D

**Comment by eluleci** [comment]
Using custom colors is told in README.md at [this location](https://github.com/eluleci/FlatUI#using-custom-colors). Also you can find the example in the [Sample Applications](https://github.com/eluleci/FlatUI/blob/master/sample/src/main/res/layout/activity_main.xml).
