### ISSUE TITLE
Have you thought about intergrating Colour?

### ISSUE THREAD

**Issue by jpotts18** [eluleci/FlatUI#4]
Hey this is a great lib! I was just wondering if you have thought about integrating [Colour](https://github.com/MatthewYork/Colours). I think it could help extend your project. I might be interested in contributing this if you think it is a good idea.

**Comment by eluleci** [comment]
I saw the Colour library and it is really good in fact. But instead of supporting other themes by default I am planing to add option for anyone to use their own color theme. Like referencing a color array.

**Comment by jpotts18** [comment]
What I liked about Colour is that it generates a Triads, Complements, etc. That way a user could put in their primary color as an input color and watch the magic begin.

`int[] complementaryColors = Colour.colorSchemeOfType(inputColor, ColorScheme.ColorSchemeComplementary);`

You can see some other examples [here](https://github.com/MatthewYork/Colours#generating-color-schemes). I really like this library, are you going to be looking for contributions?

**Comment by eluleci** [comment]
Hmm. Yes I am open to contributions. You can fork the library and add this Colour integration and we can merge after testing. But the thing is I am really busy lately so I can not spend so much time for it. But I'ld like to keep in touch with you about this feature. :)
