### ISSUE TITLE
how to use in android studio

### ISSUE THREAD

**Issue by ivanferianda** [eluleci/FlatUI#41]
hey i want to use Flatui in android studio and then after i paste
compile 'com.github.eluleci:flatui:3.0.0' in my build.gradle on my project then doesnt work nothing can you help me?sorry cause im very new for this, thanks for read my issues.

**Comment by eluleci** [comment]
Try to invalidate the cache of Android Studio from "File -> Invalidate Chaches / Restart". Also check your connection and wait until Android Studio loads the dependencies.
This is the only thing I can suggest now. 

Please think twice while opening an issue on any project again. Issues are not for these stuff.
