### ISSUE TITLE
Error ADT import

### ISSUE THREAD

**Issue by wserpas** [eluleci/FlatUI#6]
Hello, 
please i got this error while import sample project :

error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

on styles.xml

**Comment by eluleci** [comment]
Sample project is using AppCompat library which lets you use some new features with old APIs. I wanted to show how to change the ActionBar drawable in MainActivity so I used this library as well. 
You can remove the dependency to this library and it should solve the problem.
