### ISSUE TITLE
EditText change placeholder color?

### ISSUE THREAD

**Issue by jpotts18** [eluleci/FlatUI#7]
How do you change the placeholder color? I see it in your demo but I don't see it in the code. Should I be using **textColor**, **textAppearance** to set this?

**Comment by eluleci** [comment]
In the FlatEditText class there is this line
setHintTextColor(color[3]);

This is the part which sets the place holder color. Since that there is no check for "hintTextColor" usage it will always override it.

**Comment by eluleci** [comment]
i updated the library for checking the hintTextColor and textColor. you can change the version to 0.1.3 from 0.1.2 and when you use these tags it will not override anymore.
