### ISSUE TITLE
Ability to change EditText's text & hint color

### ISSUE THREAD

**Issue by aemxn** [eluleci/FlatUI#8]
Hello, 

I'd like to change the EditText text color as well as its hint color. Am I be able to do so with current build? I've tried other options such as textColor, backgroundColor, customBackgroundColor and textAppearance, but none of them works.

**Comment by eluleci** [comment]
i updated the library for checking the hintTextColor and textColor. you can change the version to 0.1.3 from 0.1.2 and when you use these tags it will not override anymore.
