### ISSUE TITLE
How can I use FlatUi in Eclipse?

### ISSUE THREAD

**Issue by jstdoit** [eluleci/FlatUI#9]

**Comment by eluleci** [comment]
You can try to download the .jar from maven http://search.maven.org/#search%7Cga%7C1%7Cflatui

But since that the library contains resource files like 'attrs.xml' and also font files, you need to copy them into your project. I didn't use them in eclipse before so I can't tell detailed explanation.

**Comment by eluleci** [comment]
I searched and found a solution at this link. 
http://stackoverflow.com/questions/21228728/androidstaggeredgrid-gradle-library-for-eclipse

I didn't have time to try it. Please let us know that you succeeded or not.

**Comment by eluleci** [comment]
@jstdoit Could you use it with Eclipse?

**Comment by jstdoit** [comment]
@eluleci I am sorry. I didn't try it. I didnot use this library now.
